import { RootDataProvider } from '@/components/providers/root-data';
import { getData } from '@/lib/api';
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { cache } from 'react';
import "./globals.css";
export const revalidate = 3600;
const get = cache((p: string) => getData(p));

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default async function RootLayout({ children }: { children: React.ReactNode }) {
  const [articles, categories] = await Promise.all([get('/data'), get('/categories')]);

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <RootDataProvider value={{ articles, categories }}>
          {children}
        </RootDataProvider>
      </body>
    </html>
  );
}
